### ISSUE TITLE
x-input作为form-item绑定keyup.enter后意外触发validate

### ISSUE THREAD

**Issue by zxj** [wmfe/xcui#133]
复现步骤：
1、x-form在x-modal中
2、x-input作为form-item
3、x-input为必填项，同时rule trigger为blur
4、x-input上绑定keyup.enter，enter处理方法提交成功后会触发x-modal的隐藏
5、由enter处理方法触发x-modal隐藏后，再次打开x-modal
6、此时，x-input的效果为rule校验失败后的效果

**Comment by clancyz** [comment]
可以在modal关闭的`on-close`钩子里面进行form的reset。
