### ISSUE TITLE
Form 表单 动态改变rules的配置（比如required属性），样式不会相应的变化

### ISSUE THREAD

**Issue by DaisyWang88** [wmfe/xcui#149]
项目里用到了form表单，其中有一个需求是“根据发票类型的不同来确定哪些字段是必填的”。
      于是根据发票类型不同来动态更改rules的配置，这里考虑到rules是多层嵌套的对象，因此为了触发更新，使用了 Object.assign({}, this.someObject)来更改rule，发现功能更新了，但是样式比如前面的红色* 没有更新。于是只能手动去额外的给它加一个样式。

**Comment by clancyz** [comment]
在这个需求里面只需要把`required`属性写在form-item上即可
