### ISSUE TITLE
v2.1.2 x-table 高度不随数据变化而更新

### ISSUE THREAD

**Issue by Leesson** [wmfe/xcui#155]
x-table的高度貌似是根据初始化数据计算的，数据源更新后table高度没有重新计算，导致不能正常展示数据。
操作步骤：
1. 初始化绑定table的data为空数组，初始化组件后更新data数据，table只显示表头，其余数据在界面上不展示，但是DOM能找到
2. 初始化绑定table的data为含有一条记录的数组，初始化组件后更新data数据，table展示表头和一条记录，其余数据DOM中能找到，只是x-table高度被固定，超出不显示。

**Comment by wanluw** [comment]
fix in #159
