### ISSUE TITLE
在 shadowDOM 中使用组件时，能否指定通过全局方法调用的组件的节点插入位置

### ISSUE THREAD

**Issue by Softor** [wmfe/xcui#178]
https://github.com/wmfe/xcui/blob/9792648c4a2539203c84689bcebb02f46fd44fec/src/components/message/msgCollection/index.js#L14

使用场景：
在 shadowDOM 里的组件中调用`this.$Message.info('message')`，message 组件插入的 DOM 位置是`document.body`。
能否将其全局配置扩展一个属性，用于指定插入的节点位置（如插入到指定的 shadowDOM 根节点）？

**Comment by clancyz** [comment]
这个可以支持，主要在考虑是否全部支持（比如其他有dropdown的一堆组件，有插入body行为的组件如`notice`）。
可以暂时先支持`message`和`notice`。
