### ISSUE TITLE
table 表头被遮盖

### ISSUE THREAD

**Issue by g8up** [wmfe/xcui#195]
https://github.com/wmfe/xcui/blob/6efee90c7195efc8072565f4ab7ed4ecc623988a/src/components/table/src/table.vue#L325

将 `x-table`置于一个隐藏(display:none)节点中初始化（比如放到一个暂未展示的 `x-modal`里），此时`headerWrapper.offsetHeight`的值为0，在表格展现时，表头(`headerWrapper`)会被表体部分（`bodyWrapper`）覆盖。

**Comment by wanluw** [comment]
fix in #196
