### ISSUE TITLE
datepicker && daterangepicker

### ISSUE THREAD

**Issue by yueyao** [wmfe/xcui#20]
- `index.js` 组件名称没有遵守驼峰式命名 `Datepicker` `Autocomplete`
- `datepicker`组件样式设置了`scoped`[建议去掉]
- `input-class` `type` 属性建议为静态属性(无`:`),无需动态绑定
```
<datepicker
      :value.sync = "date.value"
      :sep = 'date.sep'
      type="date"
      input-class = "demoCls"
      ></datepicker>
```
- 在当前月份下， 无法选择下一个月日期或者上一个月日期（即置灰的日期）。
- `datepicker - time` 首次不做任何选择，点击确定无法赋值

- `daterangepicker - time` 时间前后顺序无法校验（end<start)
- 日历icon布局尺寸有误 [demo](http://sandbox.runjs.cn/show/oa3diow0)
-  `daterangepicker - date` 样式问题：
    激活态4面圆角（正常态应为：start日期 leftTop + leftBottom圆角，end日期 rightTop + rightBottom圆角）
<img width="490" alt="2016-10-27 2 02 07" src="https://cloud.githubusercontent.com/assets/3375725/19756290/0f734f24-9c4e-11e6-9c7e-c6261cad8de9.png">

**Comment by alisa1124** [comment]
@yueyao  已修复 嘿嘿嘿～～～
