### ISSUE TITLE
PageLoading

### ISSUE THREAD

**Issue by youen123** [wmfe/xcui#22]
- 实际组件的部分属性没有列出
- demo的代码里有type属性，但是组件没有这个属性
- 从demo的代码里并不能看出子组件方法的调用方式，建议demo里附上调用的代码
- 演示按钮功能不清晰，按钮里写的stop，下面props写的是end，组件方法实际叫done，不统一
- name错了，应该是XcuiPageLoading
- 演示上没有看出inc和start的区别
- set的值的范围建议说明一下，似乎有最小限制

**Comment by MaoYuga** [comment]
fixed @youen123
