### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by alisa1124** [wmfe/xcui#23]
1、自定义样式hover样式没有办法修改，希望增加可以修改hover样式的功能
      建议：classname：hover{}就可以修改hover的样式
2、define-class 可配置属性，改变height值无法修改高度
3、昨天波波翀宇他们讨论结果，希望把scoped去掉 @MaoYuga

**Comment by MaoYuga** [comment]
fix height bug . @alisa1124 
hover problem won't fix
