### ISSUE TITLE
Input-number

### ISSUE THREAD

**Issue by xiayuxiaoyan** [wmfe/xcui#26]
@bazudragon 
一、样式显示有两个问题，如下图：
        ![image](https://cloud.githubusercontent.com/assets/7700024/19723737/30c8167c-9baf-11e6-80b0-6369c6457369.png)
        1、字数多了会被右侧的箭头覆盖，可以考虑当字数达到一定长度的时候，应该给箭头图左侧加个padding
        2、箭头左边的竖线长度没有接到底部。建议左边框高度不要写死，根据输入框的高度，响应式调整。比如百分比

二、实例提示太偏业务，应该举大众一点儿的例子
       
![image](https://cloud.githubusercontent.com/assets/7700024/19723716/1de0c324-9baf-11e6-8e3a-f5928590669e.png)

三、API问题
       1、input-value 设置input-value='8'不好使，必须使用input-value=“'8'”才可以，这个可以改成number类型，而不是邀请字符串类型。
      2、size 描述中应该说明只支持 large normal，不然用户龙椅输入具体px值。建议这个框的size最好做成可以灵活配置的入口。

**Comment by clancyz** [comment]
组件库DEMO不应包含业务术语。 @bazudragon 修改后提交pr
