### ISSUE TITLE
Progress进度条

### ISSUE THREAD

**Issue by AlbusW** [wmfe/xcui#29]
- 建议清理下组建内部不用的样式代码
````
.shine span {
          
        }
````
- 样式参数建议写上单位，为什么只提供了高度的设置，宽度选择百分数加边距？

- percent-info自定义className没有列进参数列表，class绑定有问题，默认值及传参均未生效。
![image](https://cloud.githubusercontent.com/assets/19452372/19755519/2a834c42-9c49-11e6-9f19-837ef59203d7.png)

- 建议demo增加交互性展示，单纯看着有点干呐。

**Comment by MaoYuga** [comment]
fixed
