### ISSUE TITLE
popover&tooltip

### ISSUE THREAD

**Issue by MaoYuga** [wmfe/xcui#30]
1、两个组件应拆开，实际使用的业务场景还是不同的。
2、tooltip组件的click事件可取消，tooltip实际使用场景更多是内容少、hover上去的情况。
3、popover提供了 titleclass和contentclass两个自定义类，建议压缩为一个供使用者调用。
4、建议去掉mixin ，将实际组件功能写入组件内就可以
5、建议去掉EventListener.js，使用vue中事件绑定

@bazudragon

**Comment by clancyz** [comment]
popover和tooltip在展示站中应该分为两个demo。
这部分计划重构，util里面的东东计划全部干掉。
mixin这个可以保留，因为popover和tooltip有相同的行为，这部分抽离成公共可以减小整体打包体积。
这个我来搞吧。 @MaoYuga @bazudragon
