### ISSUE TITLE
Modal样式问题

### ISSUE THREAD

**Issue by ericchan1336** [wmfe/xcui#60]
1. title的默认值居然是‘提示’，不妥，应该为空。
2. 当title为空的时候，作为separator的那条横线和关闭按钮重叠。
3. 关闭按钮的样式难看。
4. Modal在focus的时候有outline样式，应该去掉。
5. 整个窗口的内容应该加大一点padding，不然内容和border挨得太近，在footer里的那两个button上表现的尤为明显。

**Comment by ericchan1336** [comment]
4. Modal在focus的时候有outline样式，应该去掉。
5. 整个窗口的内容应该加大一点padding，不然内容和border挨得太近，在footer里的那两个button上表现的尤为明显。

**Comment by yueyao** [comment]
不符合 modal 标准样式
http://v3.bootcss.com/javascript/#modals
